In [20]:
import numpy as np
import pandas as pd

In [21]:
pd.__version__

'3.0.3'

In [22]:
df=pd.DataFrame([11,22,33])
print(df)
df1=pd.DataFrame([11,22,33], columns=['columns'])
print(df1)

    0
0  11
1  22
2  33
   columns
0       11
1       22
2       33

In [23]:
print(type(df))

<class 'pandas.DataFrame'>

In [24]:
data = {
    'Name': ['rohan', 'amit', 'suhani', 'lalita'],
    'age': [21,31,23,45],
    'Salary': [20000,34000, 25000,30000]
}
print(type(data))

<class 'dict'>

In [25]:
df=pd.DataFrame(data)
print(type(df))
print(df)

<class 'pandas.DataFrame'>
     Name  age  Salary
0   rohan   21   20000
1    amit   31   34000
2  suhani   23   25000
3  lalita   45   30000

In [26]:
print(df.head(2))
print(df.tail(2))
print(df.shape)
print(df.columns)

    Name  age  Salary
0  rohan   21   20000
1   amit   31   34000
     Name  age  Salary
2  suhani   23   25000
3  lalita   45   30000
(4, 3)
Index(['Name', 'age', 'Salary'], dtype='str')

In [27]:
df.rename(columns={'Salary': 'income'},inplace=True)
print(df)
dfr=df.rename(columns={'Salary': 'income'})
print(dfr)

     Name  age  income
0   rohan   21   20000
1    amit   31   34000
2  suhani   23   25000
3  lalita   45   30000
     Name  age  income
0   rohan   21   20000
1    amit   31   34000
2  suhani   23   25000
3  lalita   45   30000

In [28]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   age     4 non-null      int64
 2   income  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

             age        income
count   4.000000      4.000000
mean   30.000000  27250.000000
std    10.893423   6075.908711
min    21.000000  20000.000000
25%    22.500000  23750.000000
50%    27.000000  27500.000000
75%    34.500000  31000.000000
max    45.000000  34000.000000

In [29]:
df.to_csv('data.csv', index=False)

In [30]:
read=pd.read_csv('data.csv')
print(read)

     Name  age  income
0   rohan   21   20000
1    amit   31   34000
2  suhani   23   25000
3  lalita   45   30000

In [31]:
df[['Name','income']]

     Name  income
0   rohan   20000
1    amit   34000
2  suhani   25000
3  lalita   30000

In [32]:
print(df.loc[df.Name=='rohan'])
print(df.loc[(df.Name=='rohan') & (df.income>=20000)])
print(df.loc[0:2])

    Name  age  income
0  rohan   21   20000
    Name  age  income
0  rohan   21   20000
     Name  age  income
0   rohan   21   20000
1    amit   31   34000
2  suhani   23   25000

In [33]:
print(df.iloc[1])
print(df.iloc[0:2])
print(df.iloc[0:4:2])

Name       amit
age          31
income    34000
Name: 1, dtype: object
    Name  age  income
0  rohan   21   20000
1   amit   31   34000
     Name  age  income
0   rohan   21   20000
2  suhani   23   25000

In [34]:
print(df[(df['age']>25)])
print(df[(df['age']>25) & (df['income']>=32000)])

     Name  age  income
1    amit   31   34000
3  lalita   45   30000
   Name  age  income
1  amit   31   34000

In [35]:
df.where(df['age']>25)

     Name   age   income
0     NaN   NaN      NaN
1    amit  31.0  34000.0
2     NaN   NaN      NaN
3  lalita  45.0  30000.0

In [36]:
df.where(df['age']>25, other= 'Not Eligible')

           Name           age        income
0  Not Eligible  Not Eligible  Not Eligible
1          amit            31         34000
2  Not Eligible  Not Eligible  Not Eligible
3        lalita            45         30000

In [37]:
df['bonus']=df['income']*0.2
df

     Name  age  income   bonus
0   rohan   21   20000  4000.0
1    amit   31   34000  6800.0
2  suhani   23   25000  5000.0
3  lalita   45   30000  6000.0

Rows & Columns modification

In [38]:
df.loc[0, 'income']=35000
df
df.loc[df.Name== 'rohan', 'income']=34500
df
df.loc[df.Name== 'amit', 'income']=34500
df

     Name  age  income   bonus
0   rohan   21   34500  4000.0
1    amit   31   34500  6800.0
2  suhani   23   25000  5000.0
3  lalita   45   30000  6000.0

In [39]:
#df=df.drop(df[df.Name=='gian'].index)
#df.drop('amit', axis=1, inplace=True)
df

     Name  age  income   bonus
0   rohan   21   34500  4000.0
1    amit   31   34500  6800.0
2  suhani   23   25000  5000.0
3  lalita   45   30000  6000.0

In [40]:
df.sort_values(by='age', inplace=True)
print(df)
df.sort_values(by='income', ascending=False, inplace=True)
df

     Name  age  income   bonus
0   rohan   21   34500  4000.0
2  suhani   23   25000  5000.0
1    amit   31   34500  6800.0
3  lalita   45   30000  6000.0

     Name  age  income   bonus
0   rohan   21   34500  4000.0
1    amit   31   34500  6800.0
3  lalita   45   30000  6000.0
2  suhani   23   25000  5000.0

In [41]:
df[['Name','income']].sort_values(by='income', ascending=False)

     Name  income
0   rohan   34500
1    amit   34500
3  lalita   30000
2  suhani   25000

In [42]:
df['income'].dtype

dtype('int64')

In [43]:
df.isnull()

    Name    age  income  bonus
0  False  False   False  False
1  False  False   False  False
3  False  False   False  False
2  False  False   False  False

In [44]:
df.loc[df.Name=='rohan', 'Salary']= np.nan
df.drop('Salary', axis=1, inplace=True)
df

     Name  age  income   bonus
0   rohan   21   34500  4000.0
1    amit   31   34500  6800.0
3  lalita   45   30000  6000.0
2  suhani   23   25000  5000.0

In [45]:
df.loc[df.Name=='rohan', 'income']= np.nan
print(df.isnull())
df.isnull().sum()

    Name    age  income  bonus
0  False  False    True  False
1  False  False   False  False
3  False  False   False  False
2  False  False   False  False

Name      0
age       0
income    1
bonus     0
dtype: int64

In [46]:
df.fillna(0, inplace=True)
df

     Name  age   income   bonus
0   rohan   21      0.0  4000.0
1    amit   31  34500.0  6800.0
3  lalita   45  30000.0  6000.0
2  suhani   23  25000.0  5000.0

In [47]:
df['Month']=[1,1,3,3]
df

     Name  age   income   bonus  Month
0   rohan   21      0.0  4000.0      1
1    amit   31  34500.0  6800.0      1
3  lalita   45  30000.0  6000.0      3
2  suhani   23  25000.0  5000.0      3

In [48]:
print(df['Month'].value_counts())
print(df['income'].value_counts())
df.loc[df.Name=='rohan', 'income']=34000
df

Month
1    2
3    2
Name: count, dtype: int64
income
0.0        1
34500.0    1
30000.0    1
25000.0    1
Name: count, dtype: int64

     Name  age   income   bonus  Month
0   rohan   21  34000.0  4000.0      1
1    amit   31  34500.0  6800.0      1
3  lalita   45  30000.0  6000.0      3
2  suhani   23  25000.0  5000.0      3

In [49]:
df.groupby('Month')['income'].sum()

Month
1    68500.0
3    55000.0
Name: income, dtype: float64

In [50]:
df.groupby('Month').agg({'income': 'mean', 'Name':'count'})

        income  Name
Month
1      34250.0     2
3      27500.0     2

In [51]:
df3 = pd.DataFrame({'ID': [1,2,3], 'Name':['A', 'B', 'C']})
df4 = pd.DataFrame({'ID': [1,2,2,4], 'Score': [88, 96, 77, 79]})
print(df3)
print(df4)

   ID Name
0   1    A
1   2    B
2   3    C
   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [52]:
pd.concat([df3, df4], axis=0)

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [53]:
pd.concat([df3, df4], axis=1)

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [54]:
print(pd.merge(df3, df4, how='inner', on='ID'))
print(pd.merge(df3, df4, how='right', on='ID'))
print(pd.merge(df3, df4, how='left', on='ID'))

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77
   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77
3   4  NaN     79
   ID Name  Score
0   1    A   88.0
1   2    B   96.0
2   2    B   77.0
3   3    C    NaN

In [55]:
print(pd.merge(df3, df4, how='inner', left_on='ID', right_on='ID'))

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77