In [4]:
import numpy as np
import pandas as pd
dict1= {
    "name":['harry','rohan','skillf','shubh'],
    "marks":[34,78,56,29],
    "city":['Delhi', 'Pune', 'Alwar', 'Noida']
}
print(dict1)

df=pd.DataFrame(dict1)

print(df)
print(df.head(2)) 
print(df.tail(2)) 

df.to_csv('friends.csv', index=False)

print(df.describe())

{'name': ['harry', 'rohan', 'skillf', 'shubh'], 'marks': [34, 78, 56, 29], 'city': ['Delhi', 'Pune', 'Alwar', 'Noida']}
     name  marks   city
0   harry     34  Delhi
1   rohan     78   Pune
2  skillf     56  Alwar
3   shubh     29  Noida
    name  marks   city
0  harry     34  Delhi
1  rohan     78   Pune
     name  marks   city
2  skillf     56  Alwar
3   shubh     29  Noida
           marks
count   4.000000
mean   49.250000
std    22.470351
min    29.000000
25%    32.750000
50%    45.000000
75%    61.500000
max    78.000000

In [5]:

example=pd.read_csv('example.csv')
print(example)

   train no.  speed    city
0      12354     34   alwar
1      54354     26   delhi
2      23566     57  rampur
3      13455     65  mumbai

In [6]:
ser=pd.Series(np.random.rand(11),index=np.arange(11))
print(ser)
print(type(ser))

0     0.652042
1     0.176082
2     0.273438
3     0.128908
4     0.653753
5     0.056998
6     0.511115
7     0.226908
8     0.526883
9     0.530107
10    0.169176
dtype: float64
<class 'pandas.Series'>

In [7]:
df1=pd.DataFrame(np.random.rand(30,5), index=np.arange(1,31))
print(df1)

t1=type(df1)
print(t1)

           0         1         2         3         4
1   0.627917  0.904221  0.789008  0.976153  0.929604
2   0.931616  0.987573  0.761426  0.998016  0.730498
3   0.077047  0.901670  0.195689  0.326894  0.703545
4   0.208763  0.806687  0.870922  0.387121  0.573045
5   0.852290  0.118925  0.986022  0.825084  0.496648
6   0.288833  0.686923  0.482217  0.834143  0.208204
7   0.673408  0.847546  0.153613  0.981905  0.433690
8   0.306716  0.437782  0.705884  0.019197  0.539631
9   0.938381  0.051885  0.228511  0.869547  0.938360
10  0.220971  0.929311  0.513957  0.431750  0.462868
11  0.879943  0.633758  0.168404  0.258805  0.777927
12  0.905094  0.670151  0.207621  0.026782  0.692725
13  0.217714  0.631657  0.487738  0.231109  0.335144
14  0.292031  0.427306  0.603302  0.344574  0.704432
15  0.722590  0.807450  0.476621  0.212821  0.739722
16  0.492511  0.483583  0.544127  0.527842  0.194818
17  0.683348  0.723470  0.931036  0.865821  0.164505
18  0.326572  0.977168  0.750004  0.258593  0.712321
19  0.180051  0.562851  0.832849  0.076140  0.730612
20  0.175903  0.692889  0.334529  0.319461  0.666769
21  0.304642  0.636500  0.671350  0.748915  0.111637
22  0.366459  0.005514  0.119554  0.377119  0.594899
23  0.771149  0.279887  0.782485  0.743271  0.814718
24  0.563526  0.528384  0.375055  0.949351  0.934866
25  0.932805  0.112316  0.841467  0.366549  0.993155
26  0.953684  0.059346  0.615768  0.368110  0.199167
27  0.913452  0.951373  0.760534  0.376570  0.895191
28  0.730732  0.277573  0.635298  0.233700  0.716929
29  0.573561  0.588747  0.864123  0.477081  0.412516
30  0.877787  0.699521  0.817795  0.467883  0.678258
<class 'pandas.DataFrame'>

In [8]:
df1.describe()

               0          1          2          3          4
count  30.000000  30.000000  30.000000  30.000000  30.000000
mean    0.566316   0.580732   0.583564   0.496010   0.602880
std     0.293123   0.298948   0.259965   0.303211   0.252473
min     0.077047   0.005514   0.119554   0.019197   0.111637
25%     0.295184   0.429925   0.400446   0.273969   0.440985
50%     0.600739   0.635129   0.625533   0.382120   0.685491
75%     0.871413   0.807259   0.787377   0.806042   0.737445
max     0.953684   0.987573   0.986022   0.998016   0.993155

In [9]:
df1.dtypes

#df1[0][0]="name"
#df1.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [10]:
df1.T

,1,2,3,4,5,6,7,8,9,10,...,21,22,23,24,25,26,27,28,29,30
0,0.627917,0.931616,0.077047,0.208763,0.852290,0.288833,0.673408,0.306716,0.938381,0.220971,...,0.304642,0.366459,0.771149,0.563526,0.932805,0.953684,0.913452,0.730732,0.573561,0.877787
1,0.904221,0.987573,0.901670,0.806687,0.118925,0.686923,0.847546,0.437782,0.051885,0.929311,...,0.636500,0.005514,0.279887,0.528384,0.112316,0.059346,0.951373,0.277573,0.588747,0.699521
2,0.789008,0.761426,0.195689,0.870922,0.986022,0.482217,0.153613,0.705884,0.228511,0.513957,...,0.671350,0.119554,0.782485,0.375055,0.841467,0.615768,0.760534,0.635298,0.864123,0.817795
3,0.976153,0.998016,0.326894,0.387121,0.825084,0.834143,0.981905,0.019197,0.869547,0.431750,...,0.748915,0.377119,0.743271,0.949351,0.366549,0.368110,0.376570,0.233700,0.477081,0.467883
4,0.929604,0.730498,0.703545,0.573045,0.496648,0.208204,0.433690,0.539631,0.938360,0.462868,...,0.111637,0.594899,0.814718,0.934866,0.993155,0.199167,0.895191,0.716929,0.412516,0.678258

In [11]:
df2=df1
#df2[0][0]="name"
df2==df1

       0     1     2     3     4
1   True  True  True  True  True
2   True  True  True  True  True
3   True  True  True  True  True
4   True  True  True  True  True
5   True  True  True  True  True
6   True  True  True  True  True
7   True  True  True  True  True
8   True  True  True  True  True
9   True  True  True  True  True
10  True  True  True  True  True
11  True  True  True  True  True
12  True  True  True  True  True
13  True  True  True  True  True
14  True  True  True  True  True
15  True  True  True  True  True
16  True  True  True  True  True
17  True  True  True  True  True
18  True  True  True  True  True
19  True  True  True  True  True
20  True  True  True  True  True
21  True  True  True  True  True
22  True  True  True  True  True
23  True  True  True  True  True
24  True  True  True  True  True
25  True  True  True  True  True
26  True  True  True  True  True
27  True  True  True  True  True
28  True  True  True  True  True
29  True  True  True  True  True
30  True  True  True  True  True

In [12]:
df3=df1.copy()
df3

           0         1         2         3         4
1   0.627917  0.904221  0.789008  0.976153  0.929604
2   0.931616  0.987573  0.761426  0.998016  0.730498
3   0.077047  0.901670  0.195689  0.326894  0.703545
4   0.208763  0.806687  0.870922  0.387121  0.573045
5   0.852290  0.118925  0.986022  0.825084  0.496648
6   0.288833  0.686923  0.482217  0.834143  0.208204
7   0.673408  0.847546  0.153613  0.981905  0.433690
8   0.306716  0.437782  0.705884  0.019197  0.539631
9   0.938381  0.051885  0.228511  0.869547  0.938360
10  0.220971  0.929311  0.513957  0.431750  0.462868
11  0.879943  0.633758  0.168404  0.258805  0.777927
12  0.905094  0.670151  0.207621  0.026782  0.692725
13  0.217714  0.631657  0.487738  0.231109  0.335144
14  0.292031  0.427306  0.603302  0.344574  0.704432
15  0.722590  0.807450  0.476621  0.212821  0.739722
16  0.492511  0.483583  0.544127  0.527842  0.194818
17  0.683348  0.723470  0.931036  0.865821  0.164505
18  0.326572  0.977168  0.750004  0.258593  0.712321
19  0.180051  0.562851  0.832849  0.076140  0.730612
20  0.175903  0.692889  0.334529  0.319461  0.666769
21  0.304642  0.636500  0.671350  0.748915  0.111637
22  0.366459  0.005514  0.119554  0.377119  0.594899
23  0.771149  0.279887  0.782485  0.743271  0.814718
24  0.563526  0.528384  0.375055  0.949351  0.934866
25  0.932805  0.112316  0.841467  0.366549  0.993155
26  0.953684  0.059346  0.615768  0.368110  0.199167
27  0.913452  0.951373  0.760534  0.376570  0.895191
28  0.730732  0.277573  0.635298  0.233700  0.716929
29  0.573561  0.588747  0.864123  0.477081  0.412516
30  0.877787  0.699521  0.817795  0.467883  0.678258

In [13]:
df3[0][0]=4
df3
df3.loc[0,'A']=654
df3

C:\Users\Shivam Anand\AppData\Local\Temp\ipykernel_20092\659232367.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df3[0][0]=4

           0         1         2         3         4      A
1   0.627917  0.904221  0.789008  0.976153  0.929604    NaN
2   0.931616  0.987573  0.761426  0.998016  0.730498    NaN
3   0.077047  0.901670  0.195689  0.326894  0.703545    NaN
4   0.208763  0.806687  0.870922  0.387121  0.573045    NaN
5   0.852290  0.118925  0.986022  0.825084  0.496648    NaN
6   0.288833  0.686923  0.482217  0.834143  0.208204    NaN
7   0.673408  0.847546  0.153613  0.981905  0.433690    NaN
8   0.306716  0.437782  0.705884  0.019197  0.539631    NaN
9   0.938381  0.051885  0.228511  0.869547  0.938360    NaN
10  0.220971  0.929311  0.513957  0.431750  0.462868    NaN
11  0.879943  0.633758  0.168404  0.258805  0.777927    NaN
12  0.905094  0.670151  0.207621  0.026782  0.692725    NaN
13  0.217714  0.631657  0.487738  0.231109  0.335144    NaN
14  0.292031  0.427306  0.603302  0.344574  0.704432    NaN
15  0.722590  0.807450  0.476621  0.212821  0.739722    NaN
16  0.492511  0.483583  0.544127  0.527842  0.194818    NaN
17  0.683348  0.723470  0.931036  0.865821  0.164505    NaN
18  0.326572  0.977168  0.750004  0.258593  0.712321    NaN
19  0.180051  0.562851  0.832849  0.076140  0.730612    NaN
20  0.175903  0.692889  0.334529  0.319461  0.666769    NaN
21  0.304642  0.636500  0.671350  0.748915  0.111637    NaN
22  0.366459  0.005514  0.119554  0.377119  0.594899    NaN
23  0.771149  0.279887  0.782485  0.743271  0.814718    NaN
24  0.563526  0.528384  0.375055  0.949351  0.934866    NaN
25  0.932805  0.112316  0.841467  0.366549  0.993155    NaN
26  0.953684  0.059346  0.615768  0.368110  0.199167    NaN
27  0.913452  0.951373  0.760534  0.376570  0.895191    NaN
28  0.730732  0.277573  0.635298  0.233700  0.716929    NaN
29  0.573561  0.588747  0.864123  0.477081  0.412516    NaN
30  0.877787  0.699521  0.817795  0.467883  0.678258    NaN
0        NaN       NaN       NaN       NaN       NaN  654.0

In [14]:
df3.drop(0,axis=1)
df3

           0         1         2         3         4      A
1   0.627917  0.904221  0.789008  0.976153  0.929604    NaN
2   0.931616  0.987573  0.761426  0.998016  0.730498    NaN
3   0.077047  0.901670  0.195689  0.326894  0.703545    NaN
4   0.208763  0.806687  0.870922  0.387121  0.573045    NaN
5   0.852290  0.118925  0.986022  0.825084  0.496648    NaN
6   0.288833  0.686923  0.482217  0.834143  0.208204    NaN
7   0.673408  0.847546  0.153613  0.981905  0.433690    NaN
8   0.306716  0.437782  0.705884  0.019197  0.539631    NaN
9   0.938381  0.051885  0.228511  0.869547  0.938360    NaN
10  0.220971  0.929311  0.513957  0.431750  0.462868    NaN
11  0.879943  0.633758  0.168404  0.258805  0.777927    NaN
12  0.905094  0.670151  0.207621  0.026782  0.692725    NaN
13  0.217714  0.631657  0.487738  0.231109  0.335144    NaN
14  0.292031  0.427306  0.603302  0.344574  0.704432    NaN
15  0.722590  0.807450  0.476621  0.212821  0.739722    NaN
16  0.492511  0.483583  0.544127  0.527842  0.194818    NaN
17  0.683348  0.723470  0.931036  0.865821  0.164505    NaN
18  0.326572  0.977168  0.750004  0.258593  0.712321    NaN
19  0.180051  0.562851  0.832849  0.076140  0.730612    NaN
20  0.175903  0.692889  0.334529  0.319461  0.666769    NaN
21  0.304642  0.636500  0.671350  0.748915  0.111637    NaN
22  0.366459  0.005514  0.119554  0.377119  0.594899    NaN
23  0.771149  0.279887  0.782485  0.743271  0.814718    NaN
24  0.563526  0.528384  0.375055  0.949351  0.934866    NaN
25  0.932805  0.112316  0.841467  0.366549  0.993155    NaN
26  0.953684  0.059346  0.615768  0.368110  0.199167    NaN
27  0.913452  0.951373  0.760534  0.376570  0.895191    NaN
28  0.730732  0.277573  0.635298  0.233700  0.716929    NaN
29  0.573561  0.588747  0.864123  0.477081  0.412516    NaN
30  0.877787  0.699521  0.817795  0.467883  0.678258    NaN
0        NaN       NaN       NaN       NaN       NaN  654.0