In [2]:
import numpy as np
import pandas as pd

In [ ]:
#KEY_WORDS

# .str.strip()
# .str.lower()
# .str.upper()
# .str.replace()
# .replace()
# .astype()
# pd.to_numeric()
# rename()

In [9]:
data = [
    [" Ayush ", "22", "₹40,000", "Delhi"],
    ["RAHUL", "24", "₹55,000", "delhi "],
    [" Aman ", "abc", "₹45,000", "DELHI"],
    ["Neha", "25", "₹60,000", " Mumbai"]
]

df = pd.DataFrame(
    data,
    columns=["name", "age", "salary", "city"]
)
df

      name  age   salary     city
0   Ayush    22  ₹40,000    Delhi
1    RAHUL   24  ₹55,000   delhi
2    Aman   abc  ₹45,000    DELHI
3     Neha   25  ₹60,000   Mumbai

In [11]:
df["name"]=df["name"].str.strip()

df["city"]=(
    df["city"]
    .str.strip()
    .str.lower()
)   
df

    name  age   salary    city
0  Ayush   22  ₹40,000   delhi
1  RAHUL   24  ₹55,000   delhi
2   Aman  abc  ₹45,000   delhi
3   Neha   25  ₹60,000  mumbai

In [12]:
df["age"]=pd.to_numeric(
    df["age"],
    errors="coerce"
)
df

    name   age   salary    city
0  Ayush  22.0  ₹40,000   delhi
1  RAHUL  24.0  ₹55,000   delhi
2   Aman   NaN  ₹45,000   delhi
3   Neha  25.0  ₹60,000  mumbai

In [15]:
df["salary"]=(
    df["salary"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
)
df["salary"]= pd.to_numeric(df["salary"])
df

    name   age  salary    city
0  Ayush  22.0   40000   delhi
1  RAHUL  24.0   55000   delhi
2   Aman   NaN   45000   delhi
3   Neha  25.0   60000  mumbai

In [16]:
df["name"]= df["name"].str.capitalize()
df

    name   age  salary    city
0  Ayush  22.0   40000   delhi
1  Rahul  24.0   55000   delhi
2   Aman   NaN   45000   delhi
3   Neha  25.0   60000  mumbai

In [17]:
df.isna().sum()

name      0
age       1
salary    0
city      0
dtype: int64

In [37]:
data = [
    [" Ayush ", "22", "₹40,000", "Delhi"],
    ["RAHUL", "24", "₹55,000", "delhi "],
    [" Aman ", "abc", "₹45,000", "DELHI"]
]

df = pd.DataFrame(
    data,
    columns=["name", "age", "salary", "city"]
)
df

      name  age   salary    city
0   Ayush    22  ₹40,000   Delhi
1    RAHUL   24  ₹55,000  delhi
2    Aman   abc  ₹45,000   DELHI

In [38]:
df["name"]= df["name"].str.capitalize()

df["salary"]= (
    df["salary"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["salary"]= pd.to_numeric(
    df["salary"],
    errors="coerce"
)

df["age"]= pd.to_numeric(
    df["age"],
    errors="coerce"
)

df["city"]= df["city"].str.strip().str.lower()

df

      name   age  salary   city
0   ayush   22.0   40000  delhi
1    Rahul  24.0   55000  delhi
2    aman    NaN   45000  delhi

In [40]:
data = [
    [" Ayush ", "22", "₹40,000", "Delhi"],
    ["RAHUL", "24", "₹55,000", "delhi "],
    [" Aman ", "abc", "₹45,000", "DELHI"],
    ["Neha", "25", "₹60,000", " Mumbai"]
]

df = pd.DataFrame(
    data,
    columns=["name", "age", "salary", "city"]
)

df

      name  age   salary     city
0   Ayush    22  ₹40,000    Delhi
1    RAHUL   24  ₹55,000   delhi
2    Aman   abc  ₹45,000    DELHI
3     Neha   25  ₹60,000   Mumbai

In [41]:
df["name"]= df["name"].str.strip().str.lower()

df["age"]=pd.to_numeric(
    df["age"],
    errors="coerce"
)

df["salary"]=(
    df["salary"]
    .str.replace("₹","", regex=False)
    .str.replace(",","", regex=False)
)

df["salary"]= pd.to_numeric(
    df["salary"],
    errors="coerce"
)

df["city"]= df["city"].str.strip().str.lower()

df

    name   age  salary    city
0  ayush  22.0   40000   delhi
1  rahul  24.0   55000   delhi
2   aman   NaN   45000   delhi
3   neha  25.0   60000  mumbai