In [1]:
import numpy as np
import pandas as pd

In [33]:
import pandas as pd

data = [
    ["ayush", 22, 85, "Delhi"],
    ["rahul", 24, 91, "Mumbai"],
    ["aman", 21, 78, "Jaipur"],
    ["rahul", 24, 91, "Mumbai"],
    ["rohit", 23, 88, "Delhi"],
    ["aman", 21, 78, "Jaipur"]
]

df = pd.DataFrame(
    data,
    columns=["name", "age", "marks", "city"]
)

print(df)

    name  age  marks    city
0  ayush   22     85   Delhi
1  rahul   24     91  Mumbai
2   aman   21     78  Jaipur
3  rahul   24     91  Mumbai
4  rohit   23     88   Delhi
5   aman   21     78  Jaipur

In [7]:
print(df.duplicated(), '\n')

print(df.duplicated().sum(), '\n')

print(df[df.duplicated()])

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

2

    name  age  marks    city
3  rahul   24     91  Mumbai
5   aman   21     78  Jaipur

In [12]:
print(df.drop_duplicates(), '\n')
print(df, '\n')

df.drop_duplicates(inplace=True)
print(df, '\n')

    name  age  marks    city
0  ayush   22     85   Delhi
1  rahul   24     91  Mumbai
2   aman   21     78  Jaipur
4  rohit   23     88   Delhi

    name  age  marks    city
0  ayush   22     85   Delhi
1  rahul   24     91  Mumbai
2   aman   21     78  Jaipur
4  rohit   23     88   Delhi

    name  age  marks    city
0  ayush   22     85   Delhi
1  rahul   24     91  Mumbai
2   aman   21     78  Jaipur
4  rohit   23     88   Delhi

In [13]:
df.duplicated(subset=["name", "age"])

0    False
1    False
2    False
4    False
dtype: bool

In [16]:
df.duplicated(keep=False)

0    False
1     True
2     True
3     True
4    False
5     True
dtype: bool

In [18]:
df.drop_duplicates(keep="last")

    name  age  marks    city
0  ayush   22     85   Delhi
3  rahul   24     91  Mumbai
4  rohit   23     88   Delhi
5   aman   21     78  Jaipur

In [20]:
df.drop_duplicates(keep="first")

    name  age  marks    city
0  ayush   22     85   Delhi
1  rahul   24     91  Mumbai
2   aman   21     78  Jaipur
4  rohit   23     88   Delhi

In [21]:
df.drop_duplicates(keep=False)

    name  age  marks   city
0  ayush   22     85  Delhi
4  rohit   23     88  Delhi

In [22]:
df.duplicated().sum()

np.int64(2)

In [25]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [26]:
df.duplicated().sum()

np.int64(2)

In [30]:
df[df.duplicated()]

    name  age  marks    city
3  rahul   24     91  Mumbai
5   aman   21     78  Jaipur

In [32]:
df= df.drop_duplicates()
print(df)

    name  age  marks    city
0  ayush   22     85   Delhi
1  rahul   24     91  Mumbai
2   aman   21     78  Jaipur
4  rohit   23     88   Delhi

In [34]:
df.drop_duplicates(subset=["name", "city"])

    name  age  marks    city
0  ayush   22     85   Delhi
1  rahul   24     91  Mumbai
2   aman   21     78  Jaipur
4  rohit   23     88   Delhi