In [41]:
import pandas as pd

In [42]:
data= [
    ["ayush", 22, 85, "delhi"],
    ["rahul", 24, 91, "Mumbai"],
    ["aman", 21, 78, "Jaipur"],
    ["rohit", 23, 88, "Delhi"],
    ["neha", 25, 95, "Mumbai"]
]

df= pd.DataFrame(
    data,
    columns=["name", "age", "marks", "city"]
)

print(df)

df["passed"]= True

print(df)  

df["grade"]= ["B", "A", "C", "B", "A"]

print(df)

    name  age  marks    city
0  ayush   22     85   delhi
1  rahul   24     91  Mumbai
2   aman   21     78  Jaipur
3  rohit   23     88   Delhi
4   neha   25     95  Mumbai
    name  age  marks    city  passed
0  ayush   22     85   delhi    True
1  rahul   24     91  Mumbai    True
2   aman   21     78  Jaipur    True
3  rohit   23     88   Delhi    True
4   neha   25     95  Mumbai    True
    name  age  marks    city  passed grade
0  ayush   22     85   delhi    True     B
1  rahul   24     91  Mumbai    True     A
2   aman   21     78  Jaipur    True     C
3  rohit   23     88   Delhi    True     B
4   neha   25     95  Mumbai    True     A

In [43]:
df["age_after_5"]= df["age"]+5
print(df)

    name  age  marks    city  passed grade  age_after_5
0  ayush   22     85   delhi    True     B           27
1  rahul   24     91  Mumbai    True     A           29
2   aman   21     78  Jaipur    True     C           26
3  rohit   23     88   Delhi    True     B           28
4   neha   25     95  Mumbai    True     A           30

In [44]:
df["percentage"]= df["marks"]/100 * 100

df["passed"]= df["marks"]>=80

print(df)

    name  age  marks    city  passed grade  age_after_5  percentage
0  ayush   22     85   delhi    True     B           27        85.0
1  rahul   24     91  Mumbai    True     A           29        91.0
2   aman   21     78  Jaipur   False     C           26        78.0
3  rohit   23     88   Delhi    True     B           28        88.0
4   neha   25     95  Mumbai    True     A           30        95.0

In [45]:
df.insert(1, "new_passed", df["marks"]>=80)

print(df)

    name  new_passed  age  marks    city  passed grade  age_after_5  \
0  ayush        True   22     85   delhi    True     B           27
1  rahul        True   24     91  Mumbai    True     A           29
2   aman       False   21     78  Jaipur   False     C           26
3  rohit        True   23     88   Delhi    True     B           28
4   neha        True   25     95  Mumbai    True     A           30

   percentage
0        85.0
1        91.0
2        78.0
3        88.0
4        95.0

In [46]:
df= df.drop("city", axis=1)
print(df)

df= df.drop(["new_passed", "age"], axis=1)
print(df)

    name  new_passed  age  marks  passed grade  age_after_5  percentage
0  ayush        True   22     85    True     B           27        85.0
1  rahul        True   24     91    True     A           29        91.0
2   aman       False   21     78   False     C           26        78.0
3  rohit        True   23     88    True     B           28        88.0
4   neha        True   25     95    True     A           30        95.0
    name  marks  passed grade  age_after_5  percentage
0  ayush     85    True     B           27        85.0
1  rahul     91    True     A           29        91.0
2   aman     78   False     C           26        78.0
3  rohit     88    True     B           28        88.0
4   neha     95    True     A           30        95.0

In [47]:
df.drop(2, axis=0)

    name  marks  passed grade  age_after_5  percentage
0  ayush     85    True     B           27        85.0
1  rahul     91    True     A           29        91.0
3  rohit     88    True     B           28        88.0
4   neha     95    True     A           30        95.0

In [48]:
df.drop(2)

    name  marks  passed grade  age_after_5  percentage
0  ayush     85    True     B           27        85.0
1  rahul     91    True     A           29        91.0
3  rohit     88    True     B           28        88.0
4   neha     95    True     A           30        95.0

In [49]:
df.drop([1, 3])
print(df)

    name  marks  passed grade  age_after_5  percentage
0  ayush     85    True     B           27        85.0
1  rahul     91    True     A           29        91.0
2   aman     78   False     C           26        78.0
3  rohit     88    True     B           28        88.0
4   neha     95    True     A           30        95.0

In [50]:
df.drop([1, 3], inplace=True)
print(df)

    name  marks  passed grade  age_after_5  percentage
0  ayush     85    True     B           27        85.0
2   aman     78   False     C           26        78.0
4   neha     95    True     A           30        95.0

In [55]:
data= [
    ["ayush", 22, 85, "delhi"],
    ["rahul", 24, 91, "Mumbai"],
    ["aman", 21, 78, "Jaipur"],
    ["rohit", 23, 88, "Delhi"],
    ["neha", 25, 95, "Mumbai"]
]

df= pd.DataFrame(
    data,
    columns=["name", "age", "marks", "city"]
)

new_rows= pd.DataFrame([
    ["karan", 26, 89, "Pune"],
    ["riya", 22, 93, "Delhi"]
], columns=["name", "age", "marks", "city"])

df = pd.concat([df, new_rows], ignore_index=True)

print(df)

    name  age  marks    city
0  ayush   22     85   delhi
1  rahul   24     91  Mumbai
2   aman   21     78  Jaipur
3  rohit   23     88   Delhi
4   neha   25     95  Mumbai
5  karan   26     89    Pune
6   riya   22     93   Delhi

In [57]:
df=df[df["marks"]>=80]
print(df)

    name  age  marks    city
0  ayush   22     85   delhi
1  rahul   24     91  Mumbai
3  rohit   23     88   Delhi
4   neha   25     95  Mumbai
5  karan   26     89    Pune
6   riya   22     93   Delhi

In [69]:
data = [
    ["ayush", 22, 85, "Delhi"],
    ["rahul", 24, 91, "Mumbai"],
    ["aman", 21, 78, "Jaipur"],
    ["rohit", 23, 88, "Delhi"]
]

df = pd.DataFrame(
    data,
    columns=["name", "age", "marks", "city"]
)

df["passed"] = df["marks"] >= 80

df["age_after_10"] = df["age"] + 10

df.drop("city", axis=1, inplace=True)

df.drop(2, inplace=True)

df.loc[4] = ["neha", 25, 95, True, 35]

print(df)

    name  age  marks  passed  age_after_10
0  ayush   22     85    True            32
1  rahul   24     91    True            34
3  rohit   23     88    True            33
4   neha   25     95    True            35