In [9]:
import pandas as pd

In [10]:
data = [
    ["ayush", 22, 85, "Delhi"],
    ["rahul", 24, 91, "Mumbai"],
    ["aman", 21, 78, "Jaipur"],
    ["rohit", 23, 88, "Delhi"],
    ["neha", 25, 95, "Mumbai"]
]

df = pd.DataFrame(
    data,
    columns=["name", "age", "marks", "city"]
)

In [11]:
df.sort_values("marks")

    name  age  marks    city
2   aman   21     78  Jaipur
0  ayush   22     85   Delhi
3  rohit   23     88   Delhi
1  rahul   24     91  Mumbai
4   neha   25     95  Mumbai

In [12]:
df.sort_values("marks", ascending=False)

    name  age  marks    city
4   neha   25     95  Mumbai
1  rahul   24     91  Mumbai
3  rohit   23     88   Delhi
0  ayush   22     85   Delhi
2   aman   21     78  Jaipur

In [13]:
df.sort_values(
    ["city", "marks"],
    ascending=[True, False]
)

    name  age  marks    city
3  rohit   23     88   Delhi
0  ayush   22     85   Delhi
2   aman   21     78  Jaipur
4   neha   25     95  Mumbai
1  rahul   24     91  Mumbai

In [14]:
df.sort_index(ascending=False)

    name  age  marks    city
4   neha   25     95  Mumbai
3  rohit   23     88   Delhi
2   aman   21     78  Jaipur
1  rahul   24     91  Mumbai
0  ayush   22     85   Delhi

In [15]:
df.sort_values("name", inplace= True)
print(df)

    name  age  marks    city
2   aman   21     78  Jaipur
0  ayush   22     85   Delhi
4   neha   25     95  Mumbai
1  rahul   24     91  Mumbai
3  rohit   23     88   Delhi

In [17]:
import pandas as pd

data = [
    ["ayush", 22, 85, "Delhi"],
    ["rahul", 24, 91, "Mumbai"],
    ["aman", 21, 78, "Jaipur"],
    ["rohit", 23, 88, "Delhi"],
    ["neha", 25, 95, "Mumbai"]
]

df = pd.DataFrame(
    data,
    columns=["name", "age", "marks", "city"]
)

df.sort_values("marks", ascending=False)

    name  age  marks    city
4   neha   25     95  Mumbai
1  rahul   24     91  Mumbai
3  rohit   23     88   Delhi
0  ayush   22     85   Delhi
2   aman   21     78  Jaipur

In [18]:
df.sort_values("marks", ascending=False).head(3)

    name  age  marks    city
4   neha   25     95  Mumbai
1  rahul   24     91  Mumbai
3  rohit   23     88   Delhi

In [21]:
df.sort_index()

    name  age  marks    city
0  ayush   22     85   Delhi
1  rahul   24     91  Mumbai
2   aman   21     78  Jaipur
3  rohit   23     88   Delhi
4   neha   25     95  Mumbai

In [22]:
df[df["marks"]>80].sort_values(
    "marks", ascending= False
)

    name  age  marks    city
4   neha   25     95  Mumbai
1  rahul   24     91  Mumbai
3  rohit   23     88   Delhi
0  ayush   22     85   Delhi

In [24]:
df[df["city"]=="Delhi"].sort_values(
    "marks", ascending= False
).head(2)

    name  age  marks   city
3  rohit   23     88  Delhi
0  ayush   22     85  Delhi

In [25]:
df.sort_values("marks", ascending= False).head(2)

    name  age  marks    city
4   neha   25     95  Mumbai
1  rahul   24     91  Mumbai

In [ ]:
df[df["age"]>22].sort_values(
    "marks", ascending= False
)

    name  age  marks    city
4   neha   25     95  Mumbai
1  rahul   24     91  Mumbai
3  rohit   23     88   Delhi
0  ayush   22     85   Delhi
2   aman   21     78  Jaipur

In [ ]:
df.sort_values(
    ["city", "age"], ascending=[True, False]
)

    name  age  marks    city
3  rohit   23     88   Delhi
0  ayush   22     85   Delhi
2   aman   21     78  Jaipur
4   neha   25     95  Mumbai
1  rahul   24     91  Mumbai

: