In [1]:
import pandas as pd

In [2]:
data = [
    ["Ayush", 22, 85],
    ["Rahul", 24, 91],
    ["Aman", 21, 78],
    ["Rohit", 23, 88],
    ["Neha", 25, 95]
]

df = pd.DataFrame(data, columns=["name", "age", "marks"])

In [5]:
print(df["marks"].mean())
print(df["marks"].sum())
print(df["marks"].min())
print(df["marks"].max())
print(df["marks"].median())

87.4
437
78
95
88.0

In [6]:
df["marks"].describe()

count     5.000000
mean     87.400000
std       6.426508
min      78.000000
25%      85.000000
50%      88.000000
75%      91.000000
max      95.000000
Name: marks, dtype: float64

In [10]:
df[["age", "marks"]].mean()

age      23.0
marks    87.4
dtype: float64

In [11]:
df[["age", "marks"]].describe()

             age      marks
count   5.000000   5.000000
mean   23.000000  87.400000
std     1.581139   6.426508
min    21.000000  78.000000
25%    22.000000  85.000000
50%    23.000000  88.000000
75%    24.000000  91.000000
max    25.000000  95.000000

In [12]:
df[["name"]].describe()

         name
count       5
unique      5
top     Ayush
freq        1

In [17]:
df["marks"].agg(["min","max","mean"])

min     78.0
max     95.0
mean    87.4
Name: marks, dtype: float64

In [18]:
df.agg({
    "age":["min", "max", "mean"],
    "marks":["min", "max", "mean"]
})

       age  marks
min   21.0   78.0
max   25.0   95.0
mean  23.0   87.4

In [19]:
data = [
    ["Ayush", 22, 85000],
    ["Rahul", 24, 91000],
    ["Aman", 21, 78000],
    ["Rohit", 23, 88000],
    ["Neha", 25, 95000]
]

df = pd.DataFrame(data, columns=["name", "age", "salary"])

df

    name  age  salary
0  Ayush   22   85000
1  Rahul   24   91000
2   Aman   21   78000
3  Rohit   23   88000
4   Neha   25   95000

In [21]:
print(df["salary"].mean())
print(df["salary"].max())
print(df["age"].min())
print(df["salary"].median())
print(df["salary"].agg(["mean", "min", "max"]))
print(df[["age", "salary"]].describe())

87400.0
95000
21
88000.0
mean    87400.0
min     78000.0
max     95000.0
Name: salary, dtype: float64
             age        salary
count   5.000000      5.000000
mean   23.000000  87400.000000
std     1.581139   6426.507605
min    21.000000  78000.000000
25%    22.000000  85000.000000
50%    23.000000  88000.000000
75%    24.000000  91000.000000
max    25.000000  95000.000000